### ISSUE TITLE
FEATURES: Report Users and Posts Functionality

### ISSUE THREAD

**Issue by danica02** [superspike7/healthier#14]
- [x] Add Users profile
- [x] As a user, I can report another users
- [x] As an admin, I can see all user resports 
- [x] As an admin, I can delete the users account if has a malicious user details
- [x] As an admin, I can delete the user reports
- [x] As an admin, I can all see post reports to decide if the user has malicious post content 
- [x] As an admin, I can delete the report_post
- [x] Send Email to a user for violating community standard

**Comment by reyolan** [comment]
Resolved with PR #76, good job!
