### ISSUE TITLE
SUGGESTION: Dashboard UI

### ISSUE THREAD

**Issue by reyolan** [superspike7/healthier#64]
- Okay lang kahit bawasan ng button, feel ko marami masyado yung pinropose kong button placements as shown below:
![Screenshot 2022-08-06 131031](https://user-images.githubusercontent.com/94411241/183235374-9f4f728d-87f5-4893-98c3-13ef2ede216c.png)

- [x] Foods
  - [x] index
  - [x] new
- [x] Exercise
  - [x] index
  - [x] new

**Comment by reyolan** [comment]
Sa upper right pala ng daily intake, if pwede may reset button or initialize button? I don't know the right term pero ayun yung pang reset ng daily intake para back to 0 calories, 0 carbo, 0 fats, 0 protein. hehe thanks.

Also, again, there may be changes, then will consult you naman if maganda ba yun or not.

**Comment by reyolan** [comment]
Then sa Schedules ang need kong columns is yung Exercise category name, start time, end time, I think yun muna for now.

**Comment by superspike7** [comment]
noted po
